steps:
  - name: 'node:${_NODE_VERSION}'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:${_NODE_VERSION}' #trigger build
    entrypoint: 'npm'
    args: ['test']
artifacts:
    npmPackages:
    - repository: 'https://europe-west1-npm.pkg.dev/exam-prep-459213/npm-repo'
      packagePath: '.'
substitutions:
  _NODE_VERSION: '16'
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
